apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    "olm.providedAPIs: Jaeger.v1.jaegertracing.io"
  name: {{ .Values.jaeger.name }}-og
  namespace: {{ .Values.jaeger.namespace }}
spec:
  upgradeStrategy: Default
