{{- if not (lookup "operators.coreos.com/v1alpha1" "Subscription" .Values.serviceMesh.namespace .Values.serviceMesh.name) }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.serviceMesh.name }}
  namespace: {{ .Values.serviceMesh.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: {{ .Values.serviceMesh.channel }}
  installPlanApproval: {{ .Values.serviceMesh.installPlanApproval }}
  name: {{ .Values.serviceMesh.name }}
  source: {{ .Values.serviceMesh.source }}
  sourceNamespace: {{ .Values.serviceMesh.sourceNamespace }}
{{- end }}
